### ISSUE TITLE
Add support for spinning icons in QTreeWidget items

### ISSUE THREAD

**Issue by dschreij** [spyder-ide/qtawesome#116]
The spinning icon feature of QtAwesome works well in buttons and labels, but now I'm trying to use a spinning icon for QTreeWidgetItem to indicate that its children are loading. I performed the usual steps:

```python
# item contains a QTreeWidgetItem
spinner = qta.icon('fa.refresh', color='green', animation=qta.Spin(item))
item.setIcon(0, spinner)
```
but this results in the error with traceback:

```python
Traceback (most recent call last):
  File "C:\Users\dschr_000\Miniconda3\lib\site-packages\qtawesome\iconic_font.py", line 157, in paint
    self.iconic, painter, rect, mode, state, self.options)
  File "C:\Users\dschr_000\Miniconda3\lib\site-packages\qtawesome\iconic_font.py", line 82, in paint
    self._paint_icon(iconic, painter, rect, mode, state, opt)
  File "C:\Users\dschr_000\Miniconda3\lib\site-packages\qtawesome\iconic_font.py", line 127, in _paint_icon
    animation.setup(self, painter, rect)
  File "C:\Users\dschr_000\Miniconda3\lib\site-packages\qtawesome\animation.py", line 24, in setup
    if self.parent_widget not in self.info:
TypeError: unhashable type: 'QTreeWidgetItem'
```
Non-spinning QtAwesome icons work perfectly in treewidget items. Is there any way to make the spinning ones work as well? Thanks!

**Comment by ccordoba12** [comment]
@goanpeca, is this possible?

**Comment by goanpeca** [comment]
I would have to look into this. But the initial answer is it is not.
