### ISSUE TITLE
PySide6 support

### ISSUE THREAD

**Issue by WhyNotHugo** [spyder-ide/qtawesome#161]
Trying to use this fails with:

```
Traceback (most recent call last):
  File "/home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9/lib/python3.9/site-packages/qtpy/__init__.py", line 204, in <module>
    from PySide import __version__ as PYSIDE_VERSION  # analysis:ignore
  File "/home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9/lib/python3.9/site-packages/shiboken6/files.dir/shibokensupport/__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
ModuleNotFoundError: No module named 'PySide'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hugo/workspace/Hugo/screenman/test.py", line 130, in <module>
    widget = MainWindow()
  File "/home/hugo/workspace/Hugo/screenman/test.py", line 80, in __init__
    name = "/home/hugo/screenshots/2020-12-12T00:28:26,928755128+01:00.png"
  File "/home/hugo/workspace/Hugo/screenman/test.py", line 58, in __init__
    self.addAction(SaveAction(self))
  File "/home/hugo/workspace/Hugo/screenman/test.py", line 31, in __init__
    import qtawesome as qta
  File "/home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9/lib/python3.9/site-packages/shiboken6/files.dir/shibokensupport/__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
  File "/home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9/lib/python3.9/site-packages/qtawesome/__init__.py", line 20, in <module>
    from qtpy import QtCore, QtWidgets, QtGui
  File "/home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9/lib/python3.9/site-packages/shiboken6/files.dir/shibokensupport/__feature__.py", line 140, in _import
    return original_import(name, *args, **kwargs)
  File "/home/hugo/.cache/pypoetry/virtualenvs/screenman-YK8rCbov-py3.9/lib/python3.9/site-packages/qtpy/__init__.py", line 210, in <module>
    raise PythonQtError('No Qt bindings could be found')
qtpy.PythonQtError: No Qt bindings could be found

```

The latest release of PySide is packaged as `PySide6`, so this fails. Any change of adding support for it?

**Comment by stonebig** [comment]
you mean Pyside2-6 ? Spyder team doesn't expect to support Pyside2-5 before Spyder-5... somewhere in 2021.

**Comment by ccordoba12** [comment]
@WhyNotHugo, this depends on support for PySide6 in QtPy. Fortunately, someone is already giving us a hand with that in spyder-ide/qtpy#225, so I expect to release a new version in two or three weeks.

**Comment by WhyNotHugo** [comment]
@stonebig `Pyzo` seems to be something entirely different to `qtawesome`.

@ccordoba12 Interesting! I wasn't aware that `qtpy` was also a spyder project! You guys are doing lots of great stuff!

I'll follow that PR to keep in the loop, thanks!

**Comment by WhyNotHugo** [comment]
Closing in favour of https://github.com/spyder-ide/qtpy/pull/225/.

**Comment by ccordoba12** [comment]
> @ccordoba12 Interesting! I wasn't aware that qtpy was also a spyder project! You guys are doing lots of great stuff!

Thanks for your kind words!

> Closing in favour of spyder-ide/qtpy#225.

And thanks for your patience too.
