### ISSUE TITLE
font not detected in ipython; after manual tweeking unable to purge it out

### ISSUE THREAD

**Issue by DSLituiev** [spyder-ide/qtawesome#24]
Ipython console in spyder (latest dev version) said the font 'fontawesome-4.3.0.ttf' not found. 
After trying to copy it manually it complained about some json file, so i removed the font again. Now I cannot run spyder on this machine, after trying to purge it 3 times (upgrading, removing completely all directories with spyder on the machine -- nothing helps) it returns a whole bunch of errors:

Traceback (most recent call last):
  File "/usr/local/bin/spyder3", line 3, in <module>
    start_app.main()
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/start_app.py", line 119, in main
    from spyderlib import spyder
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/spyder.py", line 146, in <module>
    from spyderlib.utils.environ import WinUserEnvDialog
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/utils/environ.py", line 18, in <module>
    from spyderlib.widgets.dicteditor import DictEditor
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/widgets/dicteditor.py", line 1236, in <module>
    class DictEditor(QDialog):
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/widgets/dicteditor.py", line 1251, in DictEditor
    icon=ima.icon('dictedit'), remote=False, parent=None):
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/utils/icon_manager.py", line 231, in icon
    qta.load_font('spyder', 'spyder.ttf', 'spyder-charmap.json', directory=_resource['directory'])
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/external/qtawesome/__init__.py", line 26, in load_font
    return _instance().load_font(*args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/external/qtawesome/__init__.py", line 17, in _instance
    ('ei', 'elusiveicons-webfont.ttf', 'elusiveicons-webfont-charmap.json'))
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/external/qtawesome/iconic_font.py", line 124, in __init__
    self.load_font(*fargs)
  File "/usr/local/lib/python3.4/dist-packages/spyderlib/external/qtawesome/iconic_font.py", line 153, in load_font
    with open(os.path.join(directory, ttf_filename), 'rb') as f:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/lib/python3.4/dist-packages/spyderlib/external/qtawesome/fonts/fontawesome-4.3.0.ttf'

**Comment by ccordoba12** [comment]
@DSLituiev, how did you install Spyder?

**Comment by DSLituiev** [comment]
git clone https://github.com/spyder-ide/spyder
    cd spyder
    pip3 install .

**Comment by DSLituiev** [comment]
Seemingly something wrong happened to the symbolic link I used to run the Spyder.
Calling `python3 bootstrap.py` works now.

Thank you for help

**Comment by ccordoba12** [comment]
I imagined that you used `pip`, that's why I asked. We need to solve that, so I'm reopening this issue :-)

**Comment by SylvainCorlay** [comment]
Solved in https://github.com/spyder-ide/spyder/pull/2526
