### ISSUE TITLE
Can't run load_font method, improper arguments specified

### ISSUE THREAD

**Issue by joshburnett** [spyder-ide/qtawesome#42]
When trying to run the latest version of Spyder via bootstrap.py, I get the following traceback:

	Executing Spyder from source checkout
	Revision None, Branch: None
	01. Patched sys.path with C:\Users\usplmujbu\Dropbox\code\spyder-master
	02. PyQt4 is detected, selecting
	03. Imported Spyder 3.0.0dev
		[Python 2.7.11 64bits, Qt 4.8.7, PyQt4 (API v2) 4.11.4 on Windows]
	0x. Enforcing parent console (Windows only)
	04. Running Spyder
	Bootstrap completed in 00:00:00.9050
	Traceback (most recent call last):
	  File "C:\Users\usplmujbu\Dropbox\code\spyder-master\spyderlib\app\spyder.py", line 3130, in main
		mainwindow = run_spyder(app, options, args)
	  File "C:\Users\usplmujbu\Dropbox\code\spyder-master\spyderlib\app\spyder.py", line 3014, in run_spyder
		main = MainWindow(options)
	  File "C:\Users\usplmujbu\Dropbox\code\spyder-master\spyderlib\app\spyder.py", line 316, in __init__
		None, ima.icon('fileopen'),
	  File "C:\Users\usplmujbu\Dropbox\code\spyder-master\spyderlib\utils\icon_manager.py", line 253, in icon
		directory=_resource['directory'])
	  File "C:\Anaconda2\lib\site-packages\qtawesome\__init__.py", line 153, in load_font
		return _instance().load_font(*args, **kwargs)
	NameError: global name 'args' is not defined

Modifying the `load_font` definition on line 128 of `__init__.py` from
`def load_font(prefix, ttf_filename, charmap_filename, directory=None):`
to
`def load_font(*args, **kwargs):`
solves the problem.

**Comment by SylvainCorlay** [comment]
@joshburnett thanks for reporting. This is my bad I broke this in the last release for documentation reasons. This is now fixed in 0.3.1. Cheers,
